//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.06.24 at 11:10:16 AM CST
//

package jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for EmailLoginType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="EmailLoginType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Username" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EmailLoginType", propOrder = {

})
@XmlRootElement
public class EmailLoginType {

	@XmlElement(name = "Username", required = true)
	protected String username;
	@XmlElement(name = "Password", required = true)
	protected String password;

	/**
	 * Gets the value of the username property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * Sets the value of the username property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setUsername(String value) {
		this.username = value;
	}

	/**
	 * Gets the value of the password property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * Sets the value of the password property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setPassword(String value) {
		this.password = value;
	}

}
