//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.31 at 09:22:55 PM CST 
//


package assignment9.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DepartmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DepartmentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DepartmentManager" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DepartmentDescribe" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="DepartmentName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DepartmentAttribute" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DepartmentNo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DepartmentType", namespace = "http://www.nju.edu.cn/schema", propOrder = {
    "departmentManager",
    "departmentDescribe"
})
public class DepartmentType {

    @XmlElement(name = "DepartmentManager", required = true)
    protected String departmentManager;
    @XmlElement(name = "DepartmentDescribe", required = true)
    protected String departmentDescribe;
    @XmlAttribute(name = "DepartmentName")
    protected String departmentName;
    @XmlAttribute(name = "DepartmentAttribute")
    protected String departmentAttribute;
    @XmlAttribute(name = "DepartmentNo")
    protected String departmentNo;

    /**
     * Gets the value of the departmentManager property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartmentManager() {
        return departmentManager;
    }

    /**
     * Sets the value of the departmentManager property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartmentManager(String value) {
        this.departmentManager = value;
    }

    /**
     * Gets the value of the departmentDescribe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartmentDescribe() {
        return departmentDescribe;
    }

    /**
     * Sets the value of the departmentDescribe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartmentDescribe(String value) {
        this.departmentDescribe = value;
    }

    /**
     * Gets the value of the departmentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * Sets the value of the departmentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartmentName(String value) {
        this.departmentName = value;
    }

    /**
     * Gets the value of the departmentAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartmentAttribute() {
        return departmentAttribute;
    }

    /**
     * Sets the value of the departmentAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartmentAttribute(String value) {
        this.departmentAttribute = value;
    }

    /**
     * Gets the value of the departmentNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartmentNo() {
        return departmentNo;
    }

    /**
     * Sets the value of the departmentNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartmentNo(String value) {
        this.departmentNo = value;
    }

}
