//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.31 at 09:22:55 PM CST 
//


package assignment9.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the assignment9 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _IndividualBaseInfo_QNAME = new QName("http://www.nju.edu.cn/schema", "IndividualBaseInfo");
    private final static QName _StudentList_QNAME = new QName("http://jw.nju.edu.cn/schema", "StudentList");
    private final static QName _Student_QNAME = new QName("http://jw.nju.edu.cn/schema", "Student");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: assignment9
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StudentType }
     * 
     */
    public StudentType createStudentType() {
        return new StudentType();
    }

    /**
     * Create an instance of {@link StudentListType }
     * 
     */
    public StudentListType createStudentListType() {
        return new StudentListType();
    }

    /**
     * Create an instance of {@link CourseScoreType }
     * 
     */
    public CourseScoreType createCourseScoreType() {
        return new CourseScoreType();
    }

    /**
     * Create an instance of {@link CourseScoreListType }
     * 
     */
    public CourseScoreListType createCourseScoreListType() {
        return new CourseScoreListType();
    }

    /**
     * Create an instance of {@link ScoreType }
     * 
     */
    public ScoreType createScoreType() {
        return new ScoreType();
    }

    /**
     * Create an instance of {@link IndividualBaseInfoType }
     * 
     */
    public IndividualBaseInfoType createIndividualBaseInfoType() {
        return new IndividualBaseInfoType();
    }

    /**
     * Create an instance of {@link DepartmentType }
     * 
     */
    public DepartmentType createDepartmentType() {
        return new DepartmentType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IndividualBaseInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nju.edu.cn/schema", name = "IndividualBaseInfo")
    public JAXBElement<IndividualBaseInfoType> createIndividualBaseInfo(IndividualBaseInfoType value) {
        return new JAXBElement<IndividualBaseInfoType>(_IndividualBaseInfo_QNAME, IndividualBaseInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StudentListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jw.nju.edu.cn/schema", name = "StudentList")
    public JAXBElement<StudentListType> createStudentList(StudentListType value) {
        return new JAXBElement<StudentListType>(_StudentList_QNAME, StudentListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StudentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jw.nju.edu.cn/schema", name = "Student")
    public JAXBElement<StudentType> createStudent(StudentType value) {
        return new JAXBElement<StudentType>(_Student_QNAME, StudentType.class, null, value);
    }

}
