//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.31 at 09:22:55 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://jw.nju.edu.cn/schema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package assignment9.model;
