//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.31 at 09:22:55 PM CST 
//


package assignment9.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ScoreType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ScoreType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StudentNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RealScore" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScoreType", propOrder = {
    "studentNo",
    "realScore"
})
public class ScoreType {

    @XmlElement(name = "StudentNo", required = true)
    protected String studentNo;
    @XmlElement(name = "RealScore", required = true)
    protected String realScore;

    /**
     * Gets the value of the studentNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStudentNo() {
        return studentNo;
    }

    /**
     * Sets the value of the studentNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStudentNo(String value) {
        this.studentNo = value;
    }

    /**
     * Gets the value of the realScore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRealScore() {
        return realScore;
    }

    /**
     * Sets the value of the realScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRealScore(String value) {
        this.realScore = value;
    }

}
