//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.31 at 09:22:55 PM CST 
//


package assignment9.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StudentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StudentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Grade" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://www.nju.edu.cn/schema}IndividualBaseInfo"/>
 *         &lt;element name="CourseScoreList" type="{http://jw.nju.edu.cn/schema}CourseScoreListType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="StudentNo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StudentType", propOrder = {
    "grade",
    "individualBaseInfo",
    "courseScoreList"
})
@XmlRootElement(name="Student")
public class StudentType {

    @XmlElement(name = "Grade", required = true)
    protected String grade;
    @XmlElement(name = "IndividualBaseInfo", namespace = "http://www.nju.edu.cn/schema", required = true)
    protected IndividualBaseInfoType individualBaseInfo;
    @XmlElement(name = "CourseScoreList", required = true)
    protected CourseScoreListType courseScoreList;
    @XmlAttribute(name = "StudentNo")
    protected String studentNo;

    /**
     * Gets the value of the grade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrade() {
        return grade;
    }

    /**
     * Sets the value of the grade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrade(String value) {
        this.grade = value;
    }

    /**
     * Gets the value of the individualBaseInfo property.
     * 
     * @return
     *     possible object is
     *     {@link IndividualBaseInfoType }
     *     
     */
    public IndividualBaseInfoType getIndividualBaseInfo() {
        return individualBaseInfo;
    }

    /**
     * Sets the value of the individualBaseInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndividualBaseInfoType }
     *     
     */
    public void setIndividualBaseInfo(IndividualBaseInfoType value) {
        this.individualBaseInfo = value;
    }

    /**
     * Gets the value of the courseScoreList property.
     * 
     * @return
     *     possible object is
     *     {@link CourseScoreListType }
     *     
     */
    public CourseScoreListType getCourseScoreList() {
        return courseScoreList;
    }

    /**
     * Sets the value of the courseScoreList property.
     * 
     * @param value
     *     allowed object is
     *     {@link CourseScoreListType }
     *     
     */
    public void setCourseScoreList(CourseScoreListType value) {
        this.courseScoreList = value;
    }

    /**
     * Gets the value of the studentNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStudentNo() {
        return studentNo;
    }

    /**
     * Sets the value of the studentNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStudentNo(String value) {
        this.studentNo = value;
    }

}
